Game Features & Weekly Salaries & Rankouts
SprocketBot/sprocket pull request #184
Opened 2022-08-13 18:14 UTC by bwpikaard

2022-08-13 18:14 UTC, 0c370t commented
Task linked: [CU-2u09kdq Run Salaries Weekly](https://app.clickup.com/t/2u09kdq)

2022-08-14 16:56 UTC, 0c370t requested changes

2022-08-14 16:56 UTC, 0c370t commented on core/src/database/game/feature/feature.enum.ts
> +     * Automatically run salaries every Monday at noon.
Pedantic but this is likely going to be configurable

2022-08-14 16:56 UTC, 0c370t commented on core/src/database/game/feature/feature.enum.ts
> +     * Automatically run rankouts every Monday at noon. (Should be a dependent of AUTO_SALARIES)
Pedantic but this is likely going to be configurable

2022-08-14 16:56 UTC, 0c370t commented on core/src/elo-connector/elo-connector.consumer.ts
> +        // }))));
Remove commented code

2022-08-15 02:43 UTC, gankoji approved these changes

2022-08-18 18:42 UTC, 0c370t commented
Fix merge conflicts

2022-08-18 22:05 UTC, merged