[CU-2vtgc9d] Fix replay validation service failure if player mapping fails.
SprocketBot/sprocket pull request #198
Opened 2022-08-25 20:11 UTC by mwbrown

2022-08-25 20:11 UTC, 0c370t commented
Task linked: [CU-2vtgc9d Submitting replays that contain users not in the database breaks](https://app.clickup.com/t/2vtgc9d)

2022-08-25 23:38 UTC, bwpikaard requested changes

2022-08-25 23:38 UTC, bwpikaard commented on microservices/submission-service/src/replay-validation/replay-validation.service.ts
>                  errors: [],
Include the full list of users that failed to be found in the error array. users.filter(same as .some statement).map(user => discordId)

2022-08-26 23:48 UTC, bwpikaard requested changes

2022-08-26 23:48 UTC, bwpikaard commented on core/src/mledb/mledb-player/mledb-player.controller.ts
> +            var failedPlatforms: string[] = [];
var bad, no var 😞 
```suggestion
            const failedPlatforms: string[] = [];
```

2022-08-26 23:48 UTC, bwpikaard commented on microservices/submission-service/src/replay-validation/replay-validation.service.ts
> +            var errors: ValidationError[] = [];
`var`y bad!
```suggestion
            const errors: ValidationError[] = [];
```

2022-08-26 23:48 UTC, bwpikaard commented on microservices/submission-service/src/replay-validation/replay-validation.service.ts
> +            this.logger.error(`Unable to validate submission, couldn't map from MLE player(s) to Sprocket user by discordId:`, JSON.stringify(userIdsResponses));
I wouldn't stringify here. Mapping and joining into a string is cleaner/easier to read.

2022-08-27 15:23 UTC, bwpikaard requested changes

2022-08-27 15:23 UTC, bwpikaard commented on microservices/submission-service/src/replay-validation/replay-validation.service.ts
> +            const errors: ValidationError[] = [];
```suggestion
            // Build up a list of failed player Discord IDs to return in the error response.
            const sprocketUserErrors: ValidationError[] = [];
            
```

2022-08-27 15:23 UTC, bwpikaard commented on microservices/submission-service/src/replay-validation/replay-validation.service.ts
> +            this.logger.error(`Unable to validate submission, couldn't map from MLE player(s) to Sprocket user by discordId:`, JSON.stringify(userIdsResponses));
```suggestion
            sprocketUserErrors.forEach(err => this.logger.error(err));
```

2022-08-27 15:23 UTC, bwpikaard commented on microservices/submission-service/src/replay-validation/replay-validation.service.ts
> +                    errors.push({
```suggestion
                    sprocketUserErrors.push({
```

2022-08-27 15:23 UTC, bwpikaard commented on microservices/submission-service/src/replay-validation/replay-validation.service.ts
> +                errors: errors,
```suggestion
                errors: sprocketUserErrors,
```

2022-08-27 17:15 UTC, bwpikaard approved these changes

2022-08-28 05:41 UTC, merged