Feat/crj/ferankouttoggle
SprocketBot/sprocket pull request #215
Opened 2022-09-05 21:08 UTC by CodeRedJack

Toggle added to Player Table in Admin, pops confirmation window before toggling.

This was FE only, not currently connected to any mutation

2022-09-05 21:11 UTC, bwpikaard requested changes

2022-09-05 21:11 UTC, bwpikaard commented on clients/web/src/lib/components/molecules/scrims/AdminPlayerTable.svelte
> +                    <label class="flex"> On </label>
Remove space before and after `On`

2022-09-05 21:11 UTC, bwpikaard commented on clients/web/src/lib/components/molecules/scrims/AdminPlayerTable.svelte
> +                    <label class="flex"> Off </label>
See previous

2022-09-05 21:13 UTC, CodeRedJack commented on clients/web/src/lib/components/molecules/scrims/AdminPlayerTable.svelte
> +                    <label class="flex"> On </label>
Changed

2022-09-05 21:24 UTC, 0c370t commented
Task linked: [CU-3r8be0j Toggle Salaries/Rankouts (FE)](https://app.clickup.com/t/3r8be0j)

2022-09-05 22:53 UTC, zachstence approved these changes

2022-09-06 00:14 UTC, bwpikaard requested changes
Connect to backend.

2022-09-10 05:55 UTC, bwpikaard commented
#225

2022-09-10 05:55 UTC, closed without merging