Feat: Webhook Entity, Franchise Submission Webhook, Scrim Created Webhook
SprocketBot/sprocket pull request #283
Opened 2022-09-20 01:28 UTC by bwpikaard

2022-09-20 04:42 UTC, gankoji submitted a review, later dismissed

2022-09-20 15:09 UTC, bwpikaard commented on microservices/notification-service/src/submission/submission.service.ts
>                          fields: [
Copy report card format and split up fields

2022-09-25 22:55 UTC, zachstence requested changes

2022-09-25 22:55 UTC, zachstence commented on core/src/database/franchise/franchise_profile/franchise_profile.model.ts
> +    submissionDiscordRoleId?: string;
Lets call this `discordRoleId` because presumably it could be used for something other than submissions

2022-09-25 22:55 UTC, zachstence commented on core/src/database/franchise/game_skill_group_profile/game_skill_group_profile.model.ts
> +    scrimDiscordRoleId?: string;
Same here, `discordRoleId`

2022-09-25 22:55 UTC, zachstence commented on core/src/database/webhook/webhook/webhook.model.ts
> +@Entity({schema: "sprocket"})
Add a line break after imports

2022-09-26 02:17 UTC, gankoji submitted a review, later dismissed

2022-10-02 02:37 UTC, gankoji approved these changes

2022-10-04 01:19 UTC, merged