feat: tests
SprocketBot/sprocket pull request #337
Opened 2022-10-13 04:06 UTC by bwpikaard

2022-10-13 05:06 UTC, gankoji approved these changes

2022-10-14 21:15 UTC, zachstence commented on microservices/matchmaking-service/src/scrim/scrim.service.spec.ts
> +            const expected: Scrim = scrim;
Instead of renaming `scrim` to `expected` here, just call it `expected` on line `135`

2022-10-15 01:01 UTC, zachstence requested changes
Mainly stylistic changes, and opportunities to use Jest's `mockResolvedValueOnce()` instead of `mockImplementationOnce(async () => {})`

2022-10-15 01:02 UTC, bwpikaard commented on microservices/matchmaking-service/src/scrim/scrim.module.ts
> +    ],
Because the entire module is imported into the test "module" and needs the imports otherwise it won't work.

2022-10-15 01:02 UTC, bwpikaard commented on microservices/matchmaking-service/src/scrim/scrim.module.ts
> +    ],
It's acting as an external module.

2022-10-15 01:38 UTC, zachstence approved these changes
Absolutely beautiful

2022-10-15 01:39 UTC, merged