Datepicker
SprocketBot/sprocket pull request #428
Opened 2023-01-08 17:54 UTC by zachstence

https://user-images.githubusercontent.com/31896377/211211323-9f2bb913-9860-4d4a-98fe-7d5c88c41792.mov

2023-01-08 17:54 UTC, 0c370t commented
Task linked: [CU-2q4pxna Datepicker Atom](https://app.clickup.com/t/2q4pxna)

2023-01-08 19:42 UTC, gankoji approved these changes

2023-01-09 15:19 UTC, 0c370t commented on clients/web/src/lib/components/atoms/form/Datepicker/Datepicker.svelte
> +        --date-picker-selected-background: #FEBF2B; /* primary-500 */
https://tailwindcss.com/docs/functions-and-directives#theme

2023-01-09 23:40 UTC, bwpikaard requested changes

2023-01-09 23:40 UTC, bwpikaard commented on clients/web/src/lib/components/atoms/form/Datepicker/Datepicker.story.svelte
> +    import type { FormControlSize, FormControlState } from "../form.types";
Formatting for imports, should be no spaces

2023-01-15 04:04 UTC, merged