feat: timeline component
SprocketBot/sprocket pull request #430
Opened 2023-01-08 19:35 UTC by zachstence

https://user-images.githubusercontent.com/31896377/211215284-d2b0539a-cc3b-4230-865c-c4547ce35643.mov

2023-01-08 19:35 UTC, 0c370t commented
Task linked: [CU-2q4p9mm Timeline Atoms & Molecules](https://app.clickup.com/t/2q4p9mm)

2023-01-08 20:04 UTC, gankoji approved these changes

2023-01-09 15:25 UTC, 0c370t submitted a review, later dismissed
Code is good; circles are not centered

2023-01-09 23:39 UTC, bwpikaard requested changes

2023-01-09 23:39 UTC, bwpikaard commented on clients/web/src/lib/components/molecules/Timeline/Timeline.story.svelte
> +    import type {Hst as _Hst} from "@histoire/plugin-svelte";
Formatting?

2023-01-09 23:39 UTC, bwpikaard commented on clients/web/src/lib/components/molecules/Timeline/Timeline.story.svelte
> +    import type {Hst as _Hst} from "@histoire/plugin-svelte";
(Should have no space in brackets in imports)

2023-01-15 03:06 UTC, 0c370t approved these changes

2023-01-15 03:06 UTC, merged