Table component
SprocketBot/sprocket pull request #468
Opened 2023-03-08 03:03 UTC by zachstence

Demo:
https://user-images.githubusercontent.com/31896377/223609087-2349c8a9-b133-4b69-9a20-08fbccca3618.mov

Tanstack has a lot of other features we can implement for the table as evidenced by their examples in their docs (see screenshot), but we can add support for those as we go. This is a good base table for now
![image](https://user-images.githubusercontent.com/31896377/223609180-324ca665-bff3-466b-8e16-b64b16bfcd21.png)

2023-03-08 03:03 UTC, 0c370t commented
Task linked: [CU-2q4pwuv Table Atom](https://app.clickup.com/t/2q4pwuv)

2023-03-08 16:47 UTC, 0c370t requested changes
Tiny Tweak; otherwise looks good

2023-03-10 01:17 UTC, zachstence commented on clients/web/src/lib/components/atoms/Table/HeaderCell.svelte
> +            class="w-full h-full flex items-center justify-center gap-2 p-4 text-sm font-bold text-white uppercase {sortable && 'cursor-pointer'}"
Fixed [7a9b544](https://github.com/SprocketBot/sprocket/pull/468/commits/7a9b54474c29e516f2c3b73bfa22493bcdf3e60f)

2023-03-10 15:47 UTC, 0c370t approved these changes

2023-03-10 15:48 UTC, merged