Application Layout Start
SprocketBot/sprocket pull request #469
Opened 2023-03-10 05:08 UTC by 0c370t

2023-03-19 19:09 UTC, bwpikaard requested changes

2023-03-19 19:09 UTC, bwpikaard commented on clients/web/histoire.config.ts
> +import { HstSvelte } from "@histoire/plugin-svelte";
```suggestion
import {defineConfig} from "histoire";
import {HstSvelte} from "@histoire/plugin-svelte";
```

2023-03-19 19:09 UTC, bwpikaard commented on clients/web/histoire.config.ts
> +const { primary, gray } = palette;
```suggestion
import {palette} from "./src/lib/palette";
const {primary, gray} = palette;
```

2023-04-24 02:19 UTC, gankoji approved these changes

2023-05-30 03:28 UTC, merged